"""About author

Revision ID: 126c7c089d29
Revises: 4d6a47c16a3c
Create Date: 2022-11-30 16:27:38.555680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126c7c089d29'
down_revision = '4d6a47c16a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(length=75), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
